WIP Refactor temp exps
az-digitalag/model-vignettes pull request #60
Opened 2021-02-15 18:05 UTC by jessicaguo

Running the temp exps in the new format. Output is substantially different from previous temp_exps_biomass.Rmd. 

Why? Weather and traits should be the same, but ensemble # has increased to 1000.

2021-02-24 04:09 UTC, dlebauer requested changes
looks like there are changes that occur both here and in #59 

* in set_MA_trt.R would it make sense to have an if(posterior_id) check the database else take the local trait.mcmc.Rdata?
* I would suggest adding a simple README like https://gist.github.com/dlebauer/7a02538ac06ce4bab6354f1d226555dc#file-readme-md to the env_comparisons directory
* The modified env_comparisons/workflow_simple.R script that I modified is here https://gist.github.com/dlebauer/7a02538ac06ce4bab6354f1d226555dc#file-workflow_simple-r. I didn't want to commit these changes, but it provides some ideas about how I might remove the dependencies on files under /home/jessicaguo (and avoid replacing this with my own home directory)
 * might make sense to go ahead and check in weather files to this repo if they aren't too big? Or store them on CyVerse (or perhaps on github but not in the repository) so that they can be pulled w/ `download_file`

2021-03-19 23:43 UTC, jessicaguo commented on BioCro/DARPA/env_comparison/inputs/pecan.ch.xml
> +        <path>/home/jessicaguo/model-vignettes/BioCro/DARPA/env_comparison/inputs/weather.ch</path>
I can see why this would be important. Could this be resolved by having the weather csv files added to github?

2021-03-20 00:01 UTC, jessicaguo commented on BioCro/DARPA/env_comparison/inputs/pecan.ch.xml
> +    <dbfiles>/data/output/pecan_runs/env_comp_results/ch/dbfiles</dbfiles>
Are you suggesting a single dbfiles location across all treatments and experiments? I can see how that would be attractive for storing all past runs but allowing model outputs to be moved flexibly. But could we still easily identify which treatment/exp the posterior_id was assocaited with?

2021-03-20 00:02 UTC, jessicaguo commented on BioCro/DARPA/env_comparison/scripts/weather.R
> +load("~/sentinel-detection/data/cleaned_data/biomass/greenhouse_outdoor_biomass.Rdata")
Okay, addedthe output csvs to the commit. Probably best to have all of the inputs readily available for a PEcAn run.

2021-03-22 16:42 UTC, dlebauer commented on BioCro/DARPA/env_comparison/inputs/pecan.ch.xml
> +    <dbfiles>/data/output/pecan_runs/env_comp_results/ch/dbfiles</dbfiles>
I don't know - this is something we will have to figure out / fix / implement in order to make the treatment / site based posteriors function properly

2021-03-22 16:42 UTC, dlebauer commented on BioCro/DARPA/env_comparison/inputs/pecan.ch.xml
> +        <path>/home/jessicaguo/model-vignettes/BioCro/DARPA/env_comparison/inputs/weather.ch</path>
yes indeed!

2021-03-22 16:44 UTC, merged